
## Application.properties is where you tell your app how to behave and how to connect to things like db,azure, etc.
spring.application.name=hrmanagement

##Database connection properties
spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=hr_management_system
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name = com.microsoft.sqlserver.jdbc.SQLServerDriver

## Changes your app from running on the default port 8080
server.port = 7070

##Controls how much info spring boot prints to the console
logging.level.org.springframework = DEBUG

##Flyway
spring.flyway.locations=classpath:db/migration
# Whether to run migrations automatically
spring.flyway.enabled=true

